#	@(#)filenames.h	2.2	05/15/85	16:40:27
#  02/04/2002 RED
#             Modified to accommodate IA64 Fortran90
#NONHPUX	define	NULL	'/dev/null'
#NONHPUX	define  TTY		'/dev/tty'
#NONHPUX	define	DTAPE	'/dev/nrmt'
#NONHPUX	define	TAPELEN	1:9
#NONHPUX	define	TABLET	'/dev/tab'
#NONHPUX	define	COMMAND	'.cmd'
#NONHPUX	define	WAVFILE '.spwav'
#NONHPUX	define	WAVHEAD '.wvhed'
#NONHPUX	define	TITLE	'.spttl'
#NONHPUX	define	PLTDAT	'/usr/spool/gplot/pNNxxxxxxxxx'
#NONHPUX	define	PLTCMD	'/usr/spool/gplot/aaNNxxxxxxxxx'
#NONHPUX	define	SPLDAT	'/usr/spool/lpd/spxxxxxxxxx'
#NONHPUX	define	SPLCMD	'/usr/spool/lpd/dfxxxxxxxxx'
#NONHPUX	define	SPLTMP	'/usr/spool/lpd/tmxxxxxxxxx'
#NONHPUX	define	SPLFILE 'spooler'
#NONHPUX	define  SPOOLFL 'spoolfile'

#DEC        define  NULL    '/dev/null'
#DEC        define  TTY             '/dev/tty'
#DEC        define  DTAPE    '/dev/nrmt'
#DEC        define  TAPELEN 1:9
#DEC        define  TABLET  '/dev/tab'
#DEC        define  COMMAND '.cmd'
#DEC        define  WAVFILE '.spwav'
#DEC        define  WAVHEAD '.wvhed'
#DEC        define  TITLE   '.spttl'
#DEC        define  PLTDAT  '/usr/spool/gplot/pNNxxxxxxxxx'
#DEC        define  PLTCMD  '/usr/spool/gplot/aaNNxxxxxxxxx'
#DEC        define  SPLDAT  '/usr/spool/lpd/spxxxxxxxxx'
#DEC        define  SPLCMD  '/usr/spool/lpd/dfxxxxxxxxx'
#DEC        define  SPLTMP  '/usr/spool/lpd/tmxxxxxxxxx'
#DEC        define  SPLFILE 'spooler'
#DEC        define  SPOOLFL 'spoolfile'

#HPUX        define  NULL    '/dev/null'
#HPUX        define  TTY             '/dev/tty'
#HPUX        define  DTAPE    '/dev/nrmt'
#HPUX        define  TAPELEN 1:9
#HPUX        define  TABLET  '/dev/tab'
#HPUX        define  COMMAND '.cmd'
#HPUX        define  WAVFILE '.spwav'
#HPUX        define  WAVHEAD '.wvhed'
#HPUX        define  TITLE   '.spttl'
#HPUX        define  PLTDAT  '/usr/spool/gplot/pNNxxxxxxxxx'
#HPUX        define  PLTCMD  '/usr/spool/gplot/aaNNxxxxxxxxx'
#HPUX        define  SPLDAT  '/usr/spool/lpd/spxxxxxxxxx'
#HPUX        define  SPLCMD  '/usr/spool/lpd/dfxxxxxxxxx'
#HPUX        define  SPLTMP  '/usr/spool/lpd/tmxxxxxxxxx'
#HPUX        define  SPLFILE 'spooler'
#HPUX        define  SPOOLFL 'spoolfile'

#LINUX        define  NULL    '/dev/null'
#LINUX        define  TTY             '/dev/tty'
#LINUX        define  DTAPE    '/dev/nrmt'
#LINUX        define  TAPELEN 1:9
#LINUX        define  TABLET  '/dev/tab'
#LINUX        define  COMMAND '.cmd'
#LINUX        define  WAVFILE '.spwav'
#LINUX        define  WAVHEAD '.wvhed'
#LINUX        define  TITLE   '.spttl'
#LINUX        define  PLTDAT  '/usr/spool/gplot/pNNxxxxxxxxx'
#LINUX        define  PLTCMD  '/usr/spool/gplot/aaNNxxxxxxxxx'
#LINUX        define  SPLDAT  '/usr/spool/lpd/spxxxxxxxxx'
#LINUX        define  SPLCMD  '/usr/spool/lpd/dfxxxxxxxxx'
#LINUX        define  SPLTMP  '/usr/spool/lpd/tmxxxxxxxxx'
#LINUX        define  SPLFILE 'spooler'
#LINUX        define  SPOOLFL 'spoolfile'

#IA64HPUX        character(*), parameter :: NULL = '/dev/null'
#IA64HPUX        character(*), parameter :: TTY = '/dev/tty'
#IA64HPUX        character(*), parameter :: DTAPE = '/dev/nrmt'
#IA64HPUX        integer, dimension(9), parameter :: TAPELEN = 0
#IA64HPUX        character(*), parameter :: TABLET = '/dev/tab'
#IA64HPUX        character(*), parameter :: COMMAND = '.cmd'
#IA64HPUX        character(*), parameter :: WAVFILE = '.spwav'
#IA64HPUX        character(*), parameter :: WAVHEAD = '.wvhed'
#IA64HPUX        character(*), parameter :: TITLE = '.spttl'
#IA64HPUX        character(*), parameter :: PLTDAT = '/usr/spool/gplot/pNNxxxxxxxxx'
#IA64HPUX        character(*), parameter :: PLTCMD = '/usr/spool/gplot/aaNNxxxxxxxxx'
#IA64HPUX        character(*), parameter :: SPLDAT = '/usr/spool/lpd/spxxxxxxxxx'
#IA64HPUX        character(*), parameter :: SPLCMD = '/usr/spool/lpd/dfxxxxxxxxx'
#IA64HPUX        character(*), parameter :: SPLTMP = '/usr/spool/lpd/tmxxxxxxxxx'
#IA64HPUX        character(*), parameter :: SPLFILE = 'spooler'
#IA64HPUX        character(*), parameter :: SPOOLFL = 'spoolfile'
