#!/bin/sh
#  Script to add field spectra to an existing spd0xxx tape file
#
#
#  test for command line arguments 1, 2, and 3
#
if test $# -lt 3
then
   echo " "
   echo "syntax: fstospecpr-multiple   base-filename   spd0xxx   ending-number-of-spectra   [flag]"
   echo " "
   echo "  choose one flag (optional)"
   echo " "
   echo " valid flag: -na  =  data:  no average (2151 channels - default)"
   echo " valid flag: -av  =  data:  average    ( 717 channels)"
   echo " valid flag: -w   =  waves: no average (2151 channels ASD std wavelengths)"
   echo " valid flag: -wav =  waves: average    ( 717 channels ASD std wavelengths)"

      exit 1
fi
#
#  Set argument list
#
basename=$1
tapefile=$2
nfiles=$3
flags="-na"
#
if [ "$4" = "-av" ] || [ "$4" = "-w" ] || [ "$4" = "-wav" ]
then
   flags=$4
fi
#
#  Start file read - write loop
#
count=0
#
while test $count -le $nfiles
   do
      if test $count -le 9
         then
            extension=.00$count
         elif test $count -le 99
            then
            extension=.0$count
         else
            extension=.$count
      fi
      echo " "
      echo "------------------------------------------------"
      echo "TRANSLATING FILE:" $basename$extension
      echo "fstospecpr $basename$extension $tapefile $flags"
      fstospecpr $basename$extension $tapefile $flags
      count=`expr $count + 1`
done
#
#  finish
#
echo " "
echo "*** DONE ***"
