



     SPECPR User's Manual                     Page 8.30


_8._6._1_8.  _F_1_8:  _B_l_o_c_k _A_v_e_r_a_g_e_s _a_n_d _S_t_a_t_i_s_t_i_c_s

     Subroutine f18 averages data blocks  into  single  data
channels  and computes the statistics (standard deviation of
the mean) for each block.  The size of the block is  defined
by the user.

     The user is first asked to enter "n"  followed  by  the
blocksize.   On  the  same line, the user can also enter "a"
and the new file number to  change  the  default  wavelength
file assignment.  No further user input is required (example
n5a3 or a3n5 do the same thing).  The  block  size  must  be
less than or equal to the number of channels.

     The average of a block j is computed from the equation




                       x7_999j8 =9 (n928-n918+1)78i=n9i78R78n9299 x9i99_________



     where (n918-n928+1) = N if n928 is less than or equal to  the
number of channels.

     If errors have been included, the standard deviation is
calculated by the following




9                      Y7_999j8 =9  (n928-n918+1)7777|99|99|99|8i=n9178R78n9299 Y9i727|99|99|99|77781/29999999___________



     where Y9j8 is the new standard deviation.  If the  errors
have not been read in, the following equation is used:




9                   Y7_999j8 =99   (n928-n918+1)81/27777|99|99|99|8i=n9178R78n92999 n928-n918+178(x9i8-x7_999j8)8299________7|99|99|99|77781/29999999_________________

9







9

9                      January 26, 1984







     SPECPR User's Manual                     Page 8.31


_8._6._1_9.  _F_1_9:  _P_o_l_y_n_o_m_i_a_l _F_i_t (_1_0 _T_e_r_m)

     Special Function 19 does a least  squares  fit  to  the
data with a polynomial of the form:

               y=a918+a928x+a938x829+a948x839+...+a9n8x8n-1

9The program requests the number of term to use for the poly-
nomial fit and will currently handle up to ten terms. To run
this routine type the file id and record number of the spec-
trum you wish to fit followed by f19. The program will allow
you to change the wavelength set if the current set  is  not
the  proper  one.  The  program  then  calculates  the least
squares curve and prints the polynomial coefficients and the
reduced chi square for the fit.





































9

9                      January 26, 1984







     SPECPR User's Manual                     Page 8.32


_8._6._2_0.  _F_2_0:  _T_e_x_t _F_i_l_e _I_n_p_u_t

     Special Function 20 has two parts to  it.   First  part
reads  data  from a text file that was generated by any pro-
gram or by using the system editor.The  second  part  writes
data  from  a  specpr file into a text file. With both parts
there are options to include errors or wavelengths or both.


     Data,errors, and wavelengths may be written  either  in
standard Fortran format 'f' or 'e' , depending on the user's
option.

By a text file it is meant that it is ascii text apart  from
a  specpr  type  file.   This file contains or can contain a
list of real numbers.  In both reading  and  writing  ,  the
format  can  either  be  'f'  or  system  editor. One set of
numbers per line i.e. wavelength, data and  errors.  Without
wavelength  option,  the order is data , errors. And without
error option the order is wavelength, data

When writing the data to a specpr  record  (i.e  v123),  the
program  will  put  the error values in the next consecutive
specpr file (i.e v124).


_8._6._2_0._1.  _U_s_i_n_g _F_u_n_c_t_i_o_n _2_0

     To run function 20, type  f20   from  math  operations.
The  routine will prompt you for what part (reading or writ-
ing) you want to do.  Type  r  for reading or  w  for  writ-
ing  followed by  e  if errors are associated with the data.
Then if you are writing you are given an option for  format.
Type  'f'  for f format or 'e' for e format. Next if you are
writing, you are asked if wavelengths are  to  be  included.
Type 'y' for yes and 'return' or any other character for no.
Then you are instructed to enter the filename of the text to
which  you  will  read or write data.  Be sure that when you
are reading, the file is in your directory, or you must give
the full file name (i.e /we/smith/dataf ).  When reading the
program will promt you for the starting column that the data
begins  (e.g.  col.  1 - 80).  Default is column one(1).  If
you are writing data to a text file you will  be  asked  the
file  id  and record number of the specpr file that the data
is from (v, w, d, u, or y).  When the operation is  finished
you  have the option to redo the operation or exit.  Type  r
to redo the operation  at this point or e or x to exit.

_8._6._2_0._2.  _S_e_t_t_i_n_g _U_p _t_h_e _T_e_x_t _F_i_l_e

     There are two ways of setting up a UNIX text file  that
can be read by f20.
9

9                      January 26, 1984







     SPECPR User's Manual                     Page 8.33


     First, and the easiest is directed output.  Output  the
data  to the terminal and direct it to a file.  In your pro-
gram write to the terminal.

        write(6,10)data
 10     format(1x,1pe15.6)

or with errors

        write(6,10)data,error
 10     format(1x,1pe15.6,1pe15.6)

run program using this method

        progname > filename

where progname is the program executable file  and  filename
is the file to be read by f20.

     Second, you can write your data directly into  a  file.
You  must  open  the file and write to it.  You can open and
assign a file using this statement.

        call setfil (lun,'filename')

where lun is  an  integer  variable  for  logical  unit  and
filename  is  the  file  to be read by f20.  Write your data
using these statements.

        write(lun,10)data
 10     format(1x,1pe15.6)

or with errors

        write(lun,10)data,error
 10     format(1x,1pe15.6,1pe15.6)

the data and/or errors will be written to  the  file  called
filename  assigned to the logical unit lun.  Then you can go
to f20 and when it prompts you for the  filename  enter  the
filename you gave in your program.

     When reading, enter f20 from math operations  and  when
it  prompts  you for your input/output filename, type in the
filename of that you assigned to the text file  using  'call
setfil'  or  directed input.  The program will print out the
channel number and the data value of that channel.  The last
channel number printed is the number of channels in the file
(or the number of data values read by f20).



9

9                      January 26, 1984







     SPECPR User's Manual                     Page 8.34


_8._6._2_0._3.  _E_x_a_m_p_l_e

1)   Operate on data using you own programs:

2)   Put these values in v1234
             channel 1: 0.99
                     2: 0.90
                     3: 0.70
                     4: 0.40


3)   Write v1234 to file 'testa' using f20

4)   Run program 'reftorem <testa >testb'

5)   Read testb into specpr using f20

6)   List the 4 channels

     See table 8.6.20.3.1 for a list of programs  which  can
     be used with F20


                        Table 8.6.20.3.1

8   _______________________________________________________________
     Progs:    Author:                 Description:
    reftorem   Clark
7                         converts reflectance to
                         Kubelka-Munk remission data
                         source: /we/clark/src/refthry/reftorem.f
    remtoref   Clark
7                         converts Kubelka-Munk remission
                         data to reflectance
                         source: /we/clark/src/refthry/remtoref.f
8   _______________________________________________________________
7  |8|7|7|7|7|7|7|





9                                                                 |8|7|7|7|7|7|7|







9

















9

9                      January 26, 1984







     SPECPR User's Manual                     Page 8.35


_8._6._2_1.  _F_2_1: _C_a_l_c_u_l_a_t_e _N_t_h _T_e_r_m _P_o_l_y_n_o_m_i_a_l_s

     This routine calculates nth term polynomials where  the
maximum  number  of terms or coefficients is 256.  This rou-
tine operates on the inputed file entered from  math  opera-
tions.  Then it prompts you for a file of coefficients.  The
file of coefficients contain the values of the  coefficients
for the polynomial.


         Y(n)=C(1)+C(2)X(n)+C(3)X(n)829+C(4)X(n)839+...


Where Y is the output array, X is the input array, C is  the
coefficient array.

     To execute the f21 function, in  math  operations  type
the  file  id  and  record number of the input file and f21.
After the routine title is printed type in the file  id  and
record number of the file containing the coefficient values,
then a space, then the number of terms  of  the  polynomial.
The  program will then do the calculations and return to the
math routine prompting you for the location to put the  out-
put file and the title etc.

     You will probably want to edit  a  file  using  f14  to
enter the coefficient values in a file.

























9

9                      January 26, 1984







     SPECPR User's Manual                     Page 8.36


_8._6._2_2.  _F_2_2: _T_a_b_l_e_t _G_r_a_p_h (_T_A_B_G_R_A_F)

     This program asks the user to define a graph  by  digi-
tizing  the  limits.  Then it accepts points from the tablet
that are within the limits of the graph and converts  the  x
and y values into data values as defined by the value of the
limits of the graph.  If a digitized point  is  outside  the
bounds  of the graph, the program will say so and ask if you
want to redo the point, begin over, write the data or  exit.
If  you  want to write the data, the program will prompt you
for the file id (v, w, d, u, or y). After which the  program
will  write  in the x data values in the record equal to the
protection plus one (1), and the y values in  the  following
record after that.  The protection is also updated.

     To execute f22, type f22  from  math  operations.   The
program  will  return  with  the  title  page of f22.  Press
return to continue.  Digitize the upper left  bound  of  the
graph,  lower left bound (origin), and the lower right bound
of the graph.  The program will return with  the  values  of
the points in tablet coordinates, the amount that the points
are off perpendicular, and the angle between the  two  axis.
If these values are acceptable type "yes".  The program will
rotate the axis should  it  be  not  exactly  perpendicular.
Then  you  must  enter  the  values  of the digitized points
starting with the upper left, origin,  lower  right  points.
Then  you  must  enter the limits of the horizontal axis and
the limits of the vertical axis of your graph.

     When the above is finished the program will return with
"ENTER  POINTS  FROM  TABLET".  After which you can digitize
points from your graph.

     If you somehow enter a point that is outside the limits
of  your  graph,  the program will return with "POINT OUT OF
BOUNDS".  You have various options at this point.   Type   r
to  reenter the point.  This will not affect the data count.
Type b to begin entering the points again.  This allows  you
to  start  over  without  having  to reenter the limits etc.
Type w when finished entering points. This will put  you  in
the  writing mode to write your data to a file.  Type x will
exit you from the program.

     If you are finished entering points  from  the  tablet,
and  wish  to  write  the data, digitize a point outside the
graph.  The program will return with "POINT OUT OF  BOUNDS".
Type an w to write the data.

     To write the data, the program will prompt you to enter
the file id of the file you want the data to be written. (v,
w, d, u, or y) Then you are prompted to type in the title of
the record that will contain the x (horizontal) values, then
after that the title of  the  record  that  contains  the  y


                      January 26, 1984







     SPECPR User's Manual                     Page 8.37


(vertical)  values.  The  data is then written in the record
equal to the protection+1, if the file has the right protec-
tion.  If not it will let you know.

     After all that you will be asked  if  you  want  to  do
another  graph.   Answer  yes  or no, if no then the program
exits.













































9

9                      January 26, 1984



